name: Docker Image CI

on:
  push:
    branches: [ 'ft/gh-actions' ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        run: echo ${{steps.tag.outouts.tag}}
      #- uses: actions/checkout@v2
      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag my-image-name:id_$(git rev-parse --short HEAD)
