name: Docker Image CI

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get latest tag
        id: tag
        run: |
          TAG=$(git describe --abbrev=0 --tags)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: boris/babel:${{env.TAG}}
