name: Docker Image CI

on:
  push:
    branches: [ 'ft/gh-actions' ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Get latest tag
        run: |
          TAG=$(git describe --abbrev=0 --tags)
          echo "The tag is ${TAG}"
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        run: docker build . --file Dockerfile --tag my-image:${TAG}
