name: Docker Image CI

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        # Optionally strip `v` prefix
        strip_v: true
    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}
      
    #- uses: actions/checkout@v2
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag boris/babel:$(date +%s)
