name: Docker Image CI

on:
  push:
    branches: [ 'ft/gh-actions' ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: tag
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.ref_name}}
          path: Release
      - name: Use tag
        run: echo ${{steps.tag.outputs.name}}
      #- uses: actions/checkout@v2
      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag my-image-name:id_$(git rev-parse --short HEAD)
